{% set name = "thrift_sasl" %}
{% set version = "0.4.3" %}
{% set hash = "5bdd5b760d90a13d9b3abfce873db0425861aa8d6bf25912d3cc0467a4f773da" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - thrift >=0.10.0
    - pure-sasl >=0.6.2
    - six >=1.13.0

test:
  imports:
    - thrift_sasl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cloudera/thrift_sasl
  license: Apache-2.0
  license_file: LICENSE
  summary: Thrift SASL module that implements TSaslClientTransport
  license_family: Apache
  dev_url: https://github.com/cloudera/thrift_sasl
  doc_url: https://github.com/cloudera/thrift_sasl

extra:
  recipe-maintainers:
    - xylar
    - mariusvniekerk
    - ericdill
    - wesm
